# Generated by Django 2.2.1 on 2019-05-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190517_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default=0, verbose_name='评论内容'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='content',
            name='content',
            field=models.TextField(verbose_name='文章内容'),
        ),
    ]
