# Generated by Django 2.2.1 on 2019-05-17 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190517_1949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': '文章内容', 'verbose_name_plural': '文章内容'},
        ),
    ]
