# Generated by Django 2.2.1 on 2019-05-18 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190517_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_date'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
    ]
