# Generated by Django 2.2.1 on 2019-05-21 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190521_1525'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Img',
        ),
    ]
