# Generated by Django 2.2.1 on 2019-05-24 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_delete_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=30, verbose_name='路径')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.Article')),
            ],
            options={
                'verbose_name': '封面',
                'verbose_name_plural': '封面',
            },
        ),
    ]
